name: Publish Docker image

on:
  push:
    branches:
      - master

env:
  IMAGE: expediagroup/flyte
  MAJOR_VERSION: 1
  RUN_NUMBER: ${{ github.run_number }}

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            latest
            ${{ env.MAJOR_VERSION }}.${{ env.RUN_NUMBER }}


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
