name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build and run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.6
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14.6

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build
